Repository input-output-hk/catalyst-ci, pull requests merged in 2023-12, with the labels that each got.

#119 feat: add markdown check in check target
  Earthfile
  docs/src/appendix/important/coc.md
  docs/src/appendix/important/contributing.md
  docs/src/appendix/important/security.md
  docs/src/guides/markdown.md
  earthly/mdlint/Earthfile
  earthly/mdlint/Readme.md
Labels: ci/cd

#118 feat: convert spelling check to a standard check targets
  Earthfile
  docs/src/guides/spellcheck.md
  earthly/cspell/Earthfile
  earthly/cspell/Readme.md
Labels: ci/cd

#125 fix: clean up local markdown check
  .github/workflows/markdown-check.yml
  Earthfile
Labels: enhancement

#123 fix: remove local spellcheck targets
  .github/workflows/spell-check.yml
  Earthfile
  docs/src/guides/spellcheck.md
  earthly/cspell/Earthfile
Labels: enhancement, draft

#127 chore: remove `CP_SRC` UDC
  earthly/cspell/Earthfile
  earthly/rust/Earthfile
Labels: ci/cd

#120 feat(docs): Add Rust dependency graph generation, enable workspace indexing for Rust docs
  docs/src/guides/languages/rust.md
  earthly/rust/Earthfile
  earthly/rust/scripts/std_build.sh
  earthly/rust/stdcfgs/cargo_config.toml
  examples/rust/.cargo/config.toml
  examples/rust/Cargo.lock
  examples/rust/Cargo.toml
  examples/rust/Earthfile
  examples/rust/crates/bar/Cargo.toml
  examples/rust/crates/bar/src/lib.rs
  examples/rust/crates/foo/Cargo.toml
  examples/rust/crates/foo/benches/benchmark.rs
  examples/rust/crates/foo/src/lib.rs
  examples/rust/crates/foo/src/main.rs
  examples/rust/crates/foo/tests/integration_test.rs
Labels: ci/cd

#129 feat: add a docs target into the pipeline
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  docs/src/onboarding/index.md
Labels: enhancement, ci/cd
