Repository input-output-hk/catalyst-ci, pull requests merged in 2024-04, with the labels that each got.

#223 feat(rust): Add verbose option to rust standard build
  earthly/rust/scripts/std_build.py
Labels: enhancement

#224 feat: Update preprod snapshot
  earthly/mithril_snapshot/Earthfile
Labels: review me

#233 fix: update earthly to 0.8
  Earthfile
  actions/configure-runner/Earthfile
  actions/discover/Earthfile
  actions/install/Earthfile
  actions/merge/Earthfile
  actions/push/Earthfile
  actions/run/Earthfile
  cli/Earthfile
  cli/cmd/main.go
  cli/go.mod
  cli/go.sum
  docs/Earthfile
  docs/src/appendix/earthly.md
  docs/src/guides/docs.md
  docs/src/guides/languages/go.md
  docs/src/guides/languages/postgresql.md
  docs/src/guides/languages/python.md
  docs/src/guides/languages/rust.md
  docs/src/guides/simulate.md
  docs/src/style/index.md
  earthly/bash/Earthfile
  earthly/cspell/Earthfile
  earthly/docs/Earthfile
  earthly/go/Earthfile
  earthly/mdlint/Earthfile
  earthly/postgresql/Earthfile
  earthly/python/Earthfile
  earthly/python/Readme.md
  earthly/rust/Earthfile
  earthly/rust/Readme.md
  earthly/spectral/Earthfile
  earthly/wasm/c/Earthfile
  examples/go/Earthfile
  examples/postgresql/Earthfile
  examples/python/Earthfile
  examples/rust/Earthfile
  examples/wasm/c/Earthfile
  services/jorm-metrics-server/Earthfile
  tools/fetcher/Earthfile
  tools/updater/Earthfile
  utilities/dbviz/Earthfile
  utilities/scripts/Earthfile
Labels: enhancement, review me
