Repository input-output-hk/catalyst-ci, pull requests merged in 2024-09, with the labels that each got.

#294 feat(rust): Make rust toolchain builds faster and bump rust version to 1.80
  .config/dictionaries/project.dic
  .github/workflows/branch-pages-delete.yml
  .github/workflows/pages.yml
  .github/workflows/publish.yml
  .github/workflows/release.yml
  .github/workflows/run.yml
  .github/workflows/semantic_pull_request.yml
  .gitignore
  .secret.template
  Earthfile
  README.md
  cli/Earthfile
  cspell.json
  docs/src/appendix/earthly.md
  docs/src/guides/languages/bash.md
  docs/src/guides/languages/go.md
  docs/src/onboarding/images/github-token.png
  docs/src/onboarding/index.md
  earthly/bash/Earthfile
  earthly/docs/Earthfile
  earthly/postgresql/Earthfile
  earthly/postgresql/sql/setup-db.sql
  earthly/python/Earthfile
  earthly/rust/Earthfile
  earthly/rust/stdcfgs/deny.toml
  earthly/rust/stdcfgs/rust-toolchain.toml
  earthly/rust/tools/Earthfile
  earthly/wasm/c/Earthfile
  earthly/wasm/c/scripts/std_build.py
  examples/go/Earthfile
  examples/postgresql/migrations/V1__users.sql
  examples/postgresql/migrations/V2__addresses.sql
  examples/rust/deny.toml
  examples/rust/rust-toolchain.toml
  tools/fetcher/Earthfile
  tools/updater/Earthfile
  utilities/dbviz/deny.toml
  utilities/dbviz/rust-toolchain.toml
Labels: ci/cd

#303 feat(rust): Changes required for the chain-follower to pass CI.
  earthly/rust/stdcfgs/deny.toml
  examples/rust/deny.toml
  utilities/dbviz/deny.toml
Labels: review me

#304 feat: Enable LaTex mathematical equations format for MkDocs
  docs/src/appendix/examples/latex.md
  earthly/docs/common/javascript/mathjax.js
  earthly/docs/common/std-theme.yml
Labels: review me

#301 feat(utilities): Add a Cassandra schema to D2 diagram entity converter
  docs/Earthfile
  docs/src/appendix/examples/d2-diagrams.md
  earthly/cassandra/Earthfile
  utilities/cql-to-d2/Earthfile
  utilities/cql-to-d2/README.md
  utilities/cql-to-d2/main.py
  utilities/cql-to-d2/poetry.lock
  utilities/cql-to-d2/pyproject.toml
  utilities/cql-to-d2/tests/expected_output/test_1.d2
  utilities/cql-to-d2/tests/input/test_1.cql
Labels: ci/cd, review me

#307 fix: update flutter web test dependencies
  .gitignore
  earthly/flutter/Earthfile
  earthly/flutter/installer/Earthfile
Labels: review me

#311 feat(rust): Bump rust to 1.81
  earthly/rust/Earthfile
  earthly/rust/stdcfgs/rust-toolchain.toml
  earthly/rust/tools/Earthfile
  examples/rust/rust-toolchain.toml
  utilities/dbviz/rust-toolchain.toml
Labels: ci/cd

#313 chore(ci): cspell improve error readability
  earthly/cspell/Earthfile
Labels: review me

#314 fix(cat-ci): Pin alpine versions to try and stop containers disappearing on upstream updates
  Earthfile
  docs/src/appendix/earthly.md
  docs/src/guides/languages/bash.md
  docs/src/guides/languages/go.md
  earthly/bash/Earthfile
  earthly/docs/Earthfile
  earthly/postgresql/Earthfile
  examples/go/Earthfile
Labels: ci/cd

#317 chore(ci): Adding Playwright function
  .config/dictionaries/project.dic
  earthly/playwright/Earthfile
Labels: review me

#318 fix(cat-ci): Flutter broken CI cache
  earthly/flutter/Earthfile
  earthly/flutter/installer/Earthfile
Labels: ci/cd, review me
