Repository input-output-hk/catalyst-ci, pull requests merged in 2024-02, with the labels that each got.

#190 feat: Add `cargo-expand` to the Rust builder
  earthly/rust/Earthfile
Labels: review me

#191 feat(wasm): C base
  .config/dictionaries/project.dic
  earthly/rust/Earthfile
  earthly/wasm/c/Earthfile
  earthly/wasm/c/scripts/std_build.py
  examples/wasm/c/Earthfile
  examples/wasm/c/component.c
  examples/wasm/c/demo.wit
Labels: ci/cd, review me

#195 fix: Downgrade rust-base alpine version to 3.18
  .config/dictionaries/project.dic
  earthly/docs/Earthfile
  earthly/python/Earthfile
  earthly/rust/Earthfile
Labels: review me

#196 docs(docs): Add d2 diagram plugin to docs
  earthly/docs/Earthfile
  earthly/docs/common/std-theme.yml
  earthly/docs/poetry.lock
  earthly/docs/pyproject.toml
  earthly/python/Earthfile
  examples/python/Readme.md
Labels: documentation, enhancement, draft
