Repository input-output-hk/catalyst-ci, pull requests merged in 2024-03, with the labels that each got.

#193 feat: add python linter
  earthly/docs/Earthfile
  earthly/python/Earthfile
  earthly/python/scripts/std_checks.py
  examples/postgresql/Earthfile
  examples/python/Earthfile
  examples/python/poetry.lock
  examples/python/pyproject.toml
  examples/python/src/sum.py
Labels: good first issue, comment me

#199 feat: Move Postgres std_checks.sh script to python
  .config/dictionaries/project.dic
  earthly/postgresql/Earthfile
  earthly/postgresql/scripts/std_checks.py
  earthly/postgresql/scripts/std_checks.sh
  earthly/rust/Earthfile
  utilities/scripts/bash/colors.sh
  utilities/scripts/python/vendor_files_check.py
Labels: ci/cd, review me

#200 fix: kroki.io broken service prevents ci from passing
  .config/dictionaries/project.dic
  docs/src/appendix/examples/diagrams/invasion_plan.dot
  docs/src/appendix/examples/graphviz-diagrams.md
  docs/src/appendix/examples/kroki-diagrams.md
  docs/src/reference/workflows.md
  earthly/docs/common/javascript/massilia-graphviz.js
  earthly/docs/common/macros/include.py
  earthly/docs/common/std-theme.yml
  earthly/docs/poetry.lock
  earthly/docs/pyproject.toml
Labels: bug

#213 feat: Python builder, install `rich`
  earthly/python/Earthfile
Labels: review me

#210 fix: Downgrade cargo-deny version from failed cargo-deny `v0.14.17`
  earthly/rust/Earthfile
Labels: review me

#217 fix: Add "https://github.com/input-output-hk/catalyst-pallas.git" to deny.toml
  earthly/rust/stdcfgs/deny.toml
  examples/rust/deny.toml
  utilities/dbviz/deny.toml
Labels: review me
