Repository input-output-hk/catalyst-ci, pull requests merged in 2024-10, with the labels that each got.

#323 fix(rust): Divide the rust caches by project properly and architecture properly, and disable file fingerprints.
  earthly/rust/Earthfile
Labels: bug

#326 fix(rust): Sync standard configs bug
  earthly/rust/Earthfile
Labels: bug

#329 fix(earthly-flutter): Make sure earthly target fails when flutter tests fail
  earthly/flutter/Earthfile
Labels: ci/cd, review me

#331 refactor: update sql schema autogen tool
  .config/dictionaries/project.dic
  earthly/java/Earthfile
  earthly/postgresql/Earthfile
  earthly/postgresql/scripts/std_docs.py
  earthly/postgresql/templates/schema.md
  examples/postgresql/diagrams.json
  utilities/dbviz/.cargo/config.toml
  utilities/dbviz/.config/nextest.toml
  utilities/dbviz/Cargo.toml
  utilities/dbviz/Earthfile
  utilities/dbviz/README.md
  utilities/dbviz/clippy.toml
  utilities/dbviz/cspell.json
  utilities/dbviz/deny.toml
  utilities/dbviz/rust-toolchain.toml
  utilities/dbviz/rustfmt.toml
  utilities/dbviz/src/default_template.jinja
  utilities/dbviz/src/lib.rs
  utilities/dbviz/src/main.rs
  utilities/dbviz/src/opts.rs
  utilities/dbviz/src/postgresql.rs
  utilities/dbviz/src/schema.rs
Labels: review me

#339 feat(rust): Update disable running benchmarks with `nextest` and `llvm-cov`
  earthly/rust/scripts/std_build.py
  earthly/rust/stdcfgs/cargo_config.toml
  examples/rust/.cargo/config.toml
  examples/rust/crates/foo/benches/benchmark.rs
Labels: review me
