Repository input-output-hk/catalyst-ci, pull requests merged in 2024-01, with the labels that each got.

#141 docs(docs): Bump mkdocs and dependent library versions to current latest
  earthly/docs/poetry.lock
  earthly/docs/pyproject.toml
Labels: documentation, enhancement

#128 feat: scanning all targets related to the given `target`
  .github/workflows/ci.yml
  .github/workflows/pages.yml
  .github/workflows/publish.yml
  .github/workflows/release.yml
  .github/workflows/run.yml
  Earthfile
  actions/discover/dist/index.js
  actions/discover/dist/licenses.txt
  actions/discover/package-lock.json
  actions/discover/package.json
  actions/discover/src/discover.test.ts
  actions/discover/src/discover.ts
  actions/install/action.yml
  actions/install/dist/index.js
  actions/install/src/install.test.ts
  actions/install/src/install.ts
  actions/run/action.yml
  actions/run/dist/index.js
  actions/run/package-lock.json
  actions/run/package.json
  actions/run/src/run.test.ts
  actions/run/src/run.ts
  actions/setup/action.yml
  cli/cmd/main.go
  cli/pkg/earthfile.go
  cli/pkg/scanners/file_scanner.go
  cli/pkg/scanners/file_scanner_test.go
  docs/src/guides/languages/rust.md
  docs/src/guides/simulate.md
  docs/src/onboarding/index.md
  docs/src/reference/actions.md
  docs/src/reference/targets.md
  examples/postgresql/Earthfile
  examples/rust/Earthfile
Labels: enhancement

#140 feat: Update Rust builder, add `target` flag
  docs/src/guides/languages/rust.md
  earthly/postgresql/Earthfile
  earthly/postgresql/scripts/python
  earthly/rust/Earthfile
  earthly/rust/scripts/std_build.py
  earthly/rust/scripts/std_build.sh
  earthly/rust/scripts/std_checks.py
  earthly/rust/scripts/std_checks.sh
  earthly/rust/stdcfgs/cargo_config.toml
  earthly/rust/stdcfgs/deny.toml
  earthly/rust/stdcfgs/nextest.toml
  examples/rust/.cargo/config.toml
  examples/rust/.config/nextest.toml
  examples/rust/Cargo.toml
  examples/rust/Earthfile
  examples/rust/deny.toml
  examples/rust/rust-toolchain.toml
  utilities/dbviz/.cargo/config.toml
  utilities/dbviz/.config/nextest.toml
  utilities/dbviz/Earthfile
  utilities/dbviz/deny.toml
  utilities/nushell/Earthfile
  utilities/scripts/python/cli.py
  utilities/scripts/python/vendor_files_check.py
Labels: enhancement, ci/cd

#152 feat: openapi lint
  .spectral.yml
  Earthfile
  docs/src/guides/json_yaml_linter.md
  earthly/spectral/Earthfile
  earthly/spectral/Readme.md
  earthly/spectral/minify-json.sh
  examples/openapi/example.json
Labels: enhancement

#164 fix: how CI CLI is handled in during setup
  .github/workflows/dogfood.yml
  .github/workflows/pages.yml
  .github/workflows/publish.yml
  .github/workflows/release.yml
  .github/workflows/run.yml
  actions/install/action.yml
  actions/install/dist/index.js
  actions/install/src/install.test.ts
  actions/install/src/install.ts
  actions/run/README.md
  actions/run/dist/index.js
  actions/run/src/run.ts
  actions/setup/action.yml
  docs/src/reference/actions.md
  docs/src/style/index.md
Labels: enhancement, ci/cd

#180 chore(ci): Bump Rust Versions & Alpine Versions, add ADR for rust-versions
  Earthfile
  cli/Earthfile
  docs/src/appendix/earthly.md
  docs/src/architecture/09_architecture_decisions/0001-arch-std.md
  docs/src/architecture/09_architecture_decisions/0002-adr.md
  docs/src/architecture/09_architecture_decisions/0003-language.md
  docs/src/architecture/09_architecture_decisions/0004-spelling.md
  docs/src/architecture/09_architecture_decisions/0005-rust.md
  docs/src/architecture/09_architecture_decisions/0006-rust-cargo-lock.md
  docs/src/architecture/09_architecture_decisions/0007-minimum-rust-version-supported.md
  docs/src/guides/languages/bash.md
  docs/src/guides/languages/go.md
  earthly/bash/Earthfile
  earthly/docs/Earthfile
  earthly/docs/common/overrides/cip.html
  earthly/postgresql/Earthfile
  earthly/python/Earthfile
  earthly/rust/Earthfile
  earthly/rust/scripts/std_build.py
  earthly/rust/stdcfgs/deny.toml
  examples/go/Earthfile
  examples/rust/deny.toml
  tools/fetcher/Earthfile
  tools/updater/Earthfile
  utilities/dbviz/deny.toml
Labels: ci/cd
