Repository input-output-hk/catalyst-ci, pull requests merged in 2025-02, with the labels that each got.

#375 chore: upgrade flutter to 3.27.3
  earthly/flutter/Earthfile
  examples/flutter/example/pubspec.lock
  examples/flutter/example/pubspec.yaml
Labels: review me

#378 feat: install sqlite for flutter
  .config/dictionaries/project.dic
  earthly/flutter/Earthfile
Labels: review me

#381 chore: upgrade flutter to 3.29.0
  .config/dictionaries/project.dic
  earthly/flutter/Earthfile
  examples/flutter/example/.gitignore
  examples/flutter/example/ios/Flutter/Debug.xcconfig
  examples/flutter/example/ios/Flutter/Release.xcconfig
  examples/flutter/example/ios/Podfile
  examples/flutter/example/macos/Flutter/Flutter-Debug.xcconfig
  examples/flutter/example/macos/Flutter/Flutter-Release.xcconfig
  examples/flutter/example/macos/Podfile
  examples/flutter/example/macos/Podfile.lock
  examples/flutter/example/macos/Runner.xcodeproj/project.pbxproj
  examples/flutter/example/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  examples/flutter/example/macos/Runner.xcworkspace/contents.xcworkspacedata
  examples/flutter/example/macos/Runner/AppDelegate.swift
  examples/flutter/example/pubspec.lock
  examples/flutter/example/pubspec.yaml
Labels: review me

#380 feat(rust): Remove unneeded `orx-pseudo-default` cargo deny exception
  earthly/rust/stdcfgs/deny.toml
  examples/rust/deny.toml
Labels: review me

#383 fix: explicit https flutter fetch
  earthly/flutter/Earthfile
Labels: bug, review me

#386 feat(rust): Bump rustc version to 1.85
  earthly/rust/Earthfile
  earthly/rust/stdcfgs/rust-toolchain.toml
  earthly/rust/tools/Earthfile
  examples/rust/rust-toolchain.toml
Labels: review me, do not merge yet

#387 feat(python): Change python-base image from alpine to debian
  earthly/docs/Earthfile
  earthly/python/Earthfile
Labels: review me, do not merge yet
