Repository input-output-hk/catalyst-ci, pull requests merged in 2025-08, with the labels that each got.

#422 fix: chrome installer and reenable tests
  earthly/flutter/Earthfile
  earthly/flutter/installer/Earthfile
Labels: review me

#428 ci(general): add no-track label
  .github/labels.yml
Labels: review me

#427 ci(general): fail validation when PR is not assigned to any GitHub Pr…
  utilities/project-fields-validator/main.py
Labels: review me

#437 chore(cat-voices): upgrade flutter to 3.35.1
  earthly/flutter/Earthfile
  examples/flutter/example/android/gradle/wrapper/gradle-wrapper.properties
  examples/flutter/example/android/settings.gradle
  examples/flutter/example/ios/Flutter/AppFrameworkInfo.plist
  examples/flutter/example/ios/Podfile
  examples/flutter/example/ios/Podfile.lock
  examples/flutter/example/ios/Runner.xcodeproj/project.pbxproj
  examples/flutter/example/macos/Podfile
  examples/flutter/example/macos/Podfile.lock
  examples/flutter/example/macos/Runner.xcodeproj/project.pbxproj
  examples/flutter/example/pubspec.lock
  examples/flutter/example/pubspec.yaml
Labels: review me, refactor

#439 feat(flutter): enable generic debug files upload to sentry
  .config/dictionaries/project.dic
  earthly/flutter/Earthfile
Labels: squad: face

#444 fix(wasm/c): `wasm-c-base` and `postgres-base` build, missing `GLIBC_2.39`
  earthly/postgresql/Earthfile
  earthly/wasm/c/Earthfile
Labels: review me, do not merge yet, fyi: hermetics, rr: hermetics
