Repository input-output-hk/catalyst-ci, pull requests merged in 2025-01, with the labels that each got.

#363 fix(rust): Bump compiler to latest release
  earthly/rust/Earthfile
  earthly/rust/stdcfgs/deny.toml
  earthly/rust/stdcfgs/rust-toolchain.toml
  examples/rust/deny.toml
  examples/rust/rust-toolchain.toml
Labels: review me

#364 fix(rust): make rust doc tests not run with nightly
  earthly/rust/Earthfile
  earthly/rust/scripts/std_build.py
  earthly/rust/stdcfgs/cargo_config.toml
  examples/rust/.cargo/config.toml
  examples/rust/Cargo.toml
  utilities/scripts/python/exec_manager.py
Labels: ci/cd

#367 fix: Pin poetry version
  earthly/python/Earthfile
Labels: review me

#356 fix(flutter): flutter apt-get install & update as single command
  earthly/flutter/Earthfile
Labels: bug, review me

#368 fix: Flutter base image
  earthly/flutter/Earthfile
Labels: review me

#372 chore: fix installing Chrome x64 in Flutter setup
  earthly/flutter/installer/Earthfile
Labels: review me
