Repository input-output-hk/catalyst-ci, pull requests merged in 2025-07, with the labels that each got.

#407 fix: rust wasm codegen
  earthly/flutter_rust_bridge/Earthfile
Labels: review me

#409 chore(earthly/rust): bump wit-bindgen to 0.43
  earthly/rust/tools/Earthfile
Labels: dependencies, squad: hermes

#411 feat(wasm, python): fix Python lint and C wasm build
  .config/dictionaries/project.dic
  earthly/python/scripts/std_checks.py
  earthly/wasm/c/scripts/std_build.py
  examples/wasm/c/component.c
  examples/wasm/c/demo.wit
  utilities/scripts/python/diff.py
Labels: ci/cd

#410 feat(rust): Rust builder updates
  earthly/rust/Earthfile
  earthly/rust/stdcfgs/cargo_manifest/project.toml
  earthly/rust/stdcfgs/cargo_manifest/workspace.toml
  earthly/rust/stdcfgs/rust-toolchain.toml
  earthly/rust/stdcfgs/rustfmt.toml
  examples/rust/Cargo.toml
  examples/rust/crates/bar/src/lib.rs
  examples/rust/crates/foo/src/lib.rs
  examples/rust/rust-toolchain.toml
  examples/rust/rustfmt.toml
Labels: review me, rr: architecture

#415 feat: Implement new golang WASM binding
  earthly/go/Earthfile
  earthly/rust/tools/Earthfile
Labels: review me, squad: hermetics
